export const ADD_QUESTION = "ADD_QUESTION";
export const EDIT_QUESTION_TITLE = "EDIT_QUESTION_TITLE";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const ADD_OPTION = "ADD_OPTION";
export const EDIT_OPTION_TITLE = "EDIT_OPTION_TITLE";
export const SELECT_TYPE = "SELECT_TYPE";
export const DELETE_OPTION = "DELETE_OPTION";
export const LOADING_USER = "LOADING_USER";
export const CREATE_FORM = "CREATE_FORM";

export const GET_QUESTIONS = "GET_QUESTIONS";

export const RESPONSE_INPUT_CHANGE = "RESPONSE_INPUT_CHANGE";

export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_RESPONSE_COUNT = "GET_RESPONSE_COUNT";
