export const ADD_QUESTION = "ADD_QUESTION";
export const EDIT_QUESTION_TITLE = "EDIT_QUESTION_TITLE";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const ADD_OPTION = "ADD_OPTION";
export const EDIT_OPTION_TITLE = "EDIT_OPTION_TITLE";
export const SELECT_TYPE = "SELECT_TYPE"
export const  DELETE_OPTION = "DELETE_OPTION"